import {
  IInterventionCategoryData
} from '../types/DataTypes';
import { DrawerIcons } from './images';

export const genderData = [
  { label: 'Male', value: 'MALE' },
  { label: 'Female', value: 'FEMALE' },
  { label: 'Others', value: 'OTHERS' },
];
export const paymentStatus = [
  { label: 'Paid', value: 'PAID' },
  { label: 'Unpaid', value: 'UNPAID' },
];
export const interventionFilter = [
  { label: 'PLP', value: 'PLP' },
  { label: 'after_sales_service', value: 'After sales service' },
];




export const DrawerLinksData = [
  { name: 'edit_profile', href: 'EditProfile', icon: DrawerIcons.UserEdit },
  {
    name: 'intervention_category',
    href: 'InterventionCategory',
    icon: DrawerIcons.Category,
  },
  { name: 'contact_support', href: 'Support', icon: DrawerIcons.Support },
  { name: 'change_password', href: 'ChangePassword', icon: DrawerIcons.Shield },
  {
    name: 'terms_and_conditions',
    href: 'TermsAndConditions',
    icon: DrawerIcons.Terms,
  },
  { name: 'privacy_policy', href: 'PrivacyPolicy', icon: DrawerIcons.Privacy },
];



export const InterventionCategoryData: IInterventionCategoryData[] = [
  { name: 'PLP', price: '350.00$', id: '1' },
  { name: 'After sell service', price: '350.00$', id: '2' },
];

export const currencyData = [
  { "label": "Afghan Afghani", "value": "؋" },
  { "label": "Albanian Lek", "value": "L" },
  { "label": "Algerian Dinar", "value": "د.ج" },
  { "label": "Angolan Kwanza", "value": "Kz" },
  { "label": "Argentine Peso", "value": "$" },
  { "label": "Armenian Dram", "value": "֏" },
  { "label": "Aruban Florin", "value": "ƒ" },
  { "label": "Australian Dollar", "value": "$" },
  { "label": "Azerbaijani Manat", "value": "₼" },
  { "label": "Bahamian Dollar", "value": "$" },
  { "label": "Bahraini Dinar", "value": ".د.ب" },
  { "label": "Bangladeshi Taka", "value": "৳" },
  { "label": "Barbadian Dollar", "value": "$" },
  { "label": "Belarusian Ruble", "value": "Br" },
  { "label": "Belize Dollar", "value": "$" },
  { "label": "Bermudian Dollar", "value": "$" },
  { "label": "Bhutanese Ngultrum", "value": "Nu." },
  { "label": "Bolivian Boliviano", "value": "Bs." },
  { "label": "Bosnia and Herzegovina Convertible Mark", "value": "KM" },
  { "label": "Botswana Pula", "value": "P" },
  { "label": "Brazilian Real", "value": "R$" },
  { "label": "British Pound Sterling", "value": "£" },
  { "label": "Brunei Dollar", "value": "$" },
  { "label": "Bulgarian Lev", "value": "лв" },
  { "label": "Burundian Franc", "value": "FBu" },
  { "label": "Cambodian Riel", "value": "៛" },
  { "label": "Canadian Dollar", "value": "$" },
  { "label": "Cape Verdean Escudo", "value": "$" },
  { "label": "Cayman Islands Dollar", "value": "$" },
  { "label": "Central African CFA Franc", "value": "FCFA" },
  { "label": "Chilean Peso", "value": "$" },
  { "label": "Chinese Yuan", "value": "¥" },
  { "label": "Colombian Peso", "value": "$" },
  { "label": "Comorian Franc", "value": "CF" },
  { "label": "Congolese Franc", "value": "FC" },
  { "label": "Costa Rican Colón", "value": "₡" },
  { "label": "Croatian Kuna", "value": "kn" },
  { "label": "Cuban Peso", "value": "$" },
  { "label": "Czech Koruna", "value": "Kč" },
  { "label": "Danish Krone", "value": "kr" },
  { "label": "Djiboutian Franc", "value": "Fdj" },
  { "label": "Dominican Peso", "value": "$" },
  { "label": "Egyptian Pound", "value": "£" },
  { "label": "Eritrean Nakfa", "value": "Nfk" },
  { "label": "Ethiopian Birr", "value": "Br" },
  { "label": "Euro", "value": "€" },
  { "label": "Falkland Islands Pound", "value": "£" },
  { "label": "Fijian Dollar", "value": "$" },
  { "label": "Gambian Dalasi", "value": "D" },
  { "label": "Georgian Lari", "value": "₾" },
  { "label": "Ghanaian Cedi", "value": "₵" },
  { "label": "Gibraltar Pound", "value": "£" },
  { "label": "Guatemalan Quetzal", "value": "Q" },
  { "label": "Guinean Franc", "value": "FG" },
  { "label": "Guyanese Dollar", "value": "$" },
  { "label": "Haitian Gourde", "value": "G" },
  { "label": "Honduran Lempira", "value": "L" },
  { "label": "Hong Kong Dollar", "value": "$" },
  { "label": "Hungarian Forint", "value": "Ft" },
  { "label": "Icelandic Króna", "value": "kr" },
  { "label": "Indian Rupee", "value": "₹" },
  { "label": "Indonesian Rupiah", "value": "Rp" },
  { "label": "Iranian Rial", "value": "﷼" },
  { "label": "Iraqi Dinar", "value": "ع.د" },
  { "label": "Israeli New Shekel", "value": "₪" },
  { "label": "Jamaican Dollar", "value": "$" },
  { "label": "Japanese Yen", "value": "¥" },
  { "label": "Jordanian Dinar", "value": "د.ا" },
  { "label": "Kazakhstani Tenge", "value": "₸" },
  { "label": "Kenyan Shilling", "value": "Sh" },
  { "label": "Kuwaiti Dinar", "value": "د.ك" },
  { "label": "Kyrgyzstani Som", "value": "с" },
  { "label": "Lao Kip", "value": "₭" },
  { "label": "Lebanese Pound", "value": "ل.ل" },
  { "label": "Lesotho Loti", "value": "L" },
  { "label": "Liberian Dollar", "value": "$" },
  { "label": "Libyan Dinar", "value": "ل.د" },
  { "label": "Macanese Pataca", "value": "P" },
  { "label": "Macedonian Denar", "value": "ден" },
  { "label": "Malagasy Ariary", "value": "Ar" },
  { "label": "Malawian Kwacha", "value": "MK" },
  { "label": "Malaysian Ringgit", "value": "RM" },
  { "label": "Maldivian Rufiyaa", "value": ".ރ" },
  { "label": "Mauritanian Ouguiya", "value": "UM" },
  { "label": "Mauritian Rupee", "value": "₨" },
  { "label": "Mexican Peso", "value": "$" },
  { "label": "Moldovan Leu", "value": "L" },
  { "label": "Mongolian Tögrög", "value": "₮" },
  { "label": "Moroccan Dirham", "value": "د.م." },
  { "label": "Mozambican Metical", "value": "MT" },
  { "label": "Myanmar Kyat", "value": "K" },
  { "label": "Namibian Dollar", "value": "$" },
  { "label": "Nepalese Rupee", "value": "₨" },
  { "label": "Netherlands Antillean Guilder", "value": "ƒ" },
  { "label": "New Taiwan Dollar", "value": "$" },
  { "label": "New Zealand Dollar", "value": "$" },
  { "label": "Nicaraguan Córdoba", "value": "C$" },
  { "label": "Nigerian Naira", "value": "₦" },
  { "label": "North Korean Won", "value": "₩" },
  { "label": "Norwegian Krone", "value": "kr" },
  { "label": "Omani Rial", "value": "ر.ع." },
  { "label": "Pakistani Rupee", "value": "₨" },
  { "label": "Panamanian Balboa", "value": "B/." },
  { "label": "Papua New Guinean Kina", "value": "K" },
  { "label": "Paraguayan Guaraní", "value": "₲" },
  { "label": "Peruvian Sol", "value": "S/" },
  { "label": "Philippine Peso", "value": "₱" },
  { "label": "Polish Złoty", "value": "zł" },
  { "label": "Qatari Riyal", "value": "ر.ق" },
  { "label": "Romanian Leu", "value": "lei" },
  { "label": "Russian Ruble", "value": "₽" },
  { "label": "Rwandan Franc", "value": "FRw" },
  { "label": "Saint Helena Pound", "value": "£" },
  { "label": "Samoan Tālā", "value": "T" },
  { "label": "São Tomé and Príncipe Dobra", "value": "Db" },
  { "label": "Saudi Riyal", "value": "ر.س" },
  { "label": "Serbian Dinar", "value": "дин." },
  { "label": "Seychellois Rupee", "value": "₨" },
  { "label": "Sierra Leonean Leone", "value": "Le" },
  { "label": "Singapore Dollar", "value": "$" },
  { "label": "Solomon Islands Dollar", "value": "$" },
  { "label": "Somali Shilling", "value": "Sh" },
  { "label": "South African Rand", "value": "R" },
  { "label": "South Korean Won", "value": "₩" },
  { "label": "South Sudanese Pound", "value": "£" },
  { "label": "Sri Lankan Rupee", "value": "Rs" },
  { "label": "Sudanese Pound", "value": "ج.س." },
  { "label": "Surinamese Dollar", "value": "$" },
  { "label": "Swazi Lilangeni", "value": "L" },
  { "label": "Swedish Krona", "value": "kr" },
  { "label": "Swiss Franc", "value": "Fr" },
  { "label": "Syrian Pound", "value": "£" },
  { "label": "Tajikistani Somoni", "value": "ЅМ" },
  { "label": "Tanzanian Shilling", "value": "Sh" },
  { "label": "Thai Baht", "value": "฿" },
  { "label": "Tongan Paʻanga", "value": "T$" },
  { "label": "Trinidad and Tobago Dollar", "value": "$" },
  { "label": "Tunisian Dinar", "value": "د.ت" },
  { "label": "Turkish Lira", "value": "₺" },
  { "label": "Turkmenistan Manat", "value": "m" },
  { "label": "Ugandan Shilling", "value": "Sh" },
  { "label": "Ukrainian Hryvnia", "value": "₴" },
  { "label": "United Arab Emirates Dirham", "value": "د.إ" },
  { "label": "United States Dollar", "value": "$" },
  { "label": "Uruguayan Peso", "value": "$" },
  { "label": "Uzbekistani Soʻm", "value": "so'm" },
  { "label": "Vanuatu Vatu", "value": "Vt" },
  { "label": "Venezuelan Bolívar", "value": "Bs F" },
  { "label": "Vietnamese Đồng", "value": "₫" },
  { "label": "West African CFA Franc", "value": "CFA" },
  { "label": "Yemeni Rial", "value": "﷼" },
  { "label": "Zambian Kwacha", "value": "ZK" },
  { "label": "Zimbabwean Dollar", "value": "$" }
]